name: Test

on: [push, pull_request]
env:
  DOCKER_TARGET_PLATFORM: "linux/amd64"

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
      - run: "bundle install"
      - run: "bundle exec rake"

      - name: Build Docker image
        run: docker buildx build --platform=${DOCKER_TARGET_PLATFORM} -t pactfoundation/pact-broker:latest .

      - name: Integration tests
        run: script/test.sh
